services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_bank
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql

  python:
    build: .
    container_name: python
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: world_bank
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./notebooks:/app/notebooks

volumes:
  postgres_data: